#!/bin/python3

import os
import subprocess
import sys

from inginious import feedback

lib_folder = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                          "$common/git_unittest")
sys.path.append(lib_folder)
lib_folder = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                          "/course/common/git_unittest")
sys.path.append(lib_folder)
from utils import _, unzip_task, unzip_solution

grade = 100.0

# Git-branch-merge subproblem
student_submission = unzip_task(task_id="git-branch-merge", expected_subpaths=["clone", "clone/.git", "bare.git"])
solution = unzip_solution(task_id="git-branch-merge")
feedback_str = ""
if student_submission is not None:
    cmd = ["python3", "/course/common/git_unittest/test.py", os.path.join(solution, "clone"), os.path.join(student_submission, "clone")]
    pid = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    out, err = pid.communicate()
    if pid.wait() == 0:
        feedback_str += _("Repo local\n\n-----------------\n\n") + _("Bonne réponse")
    else:
        feedback_str += _("Repo local\n\n-----------------\n\n") + err.decode("utf-8")
        grade -= 50.

    cmd = ["python3", "/course/common/git_unittest/test.py", os.path.join(solution, "bare.git"),
           os.path.join(student_submission, "bare.git")]
    pid = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    out, err = pid.communicate()
    if pid.wait() == 0:
        feedback_str += _("\n\n-----------------\n\nRepo distant\n\n-----------------\n\n") + _("Bonne réponse")
    else:
        feedback_str += _("\n\n-----------------\n\nRepo distant\n\n-----------------\n\n") + err.decode("utf-8")
        grade -= 50.
    if grade == 100:
        feedback.set_problem_result("success", "git-branch-merge")
    else:
        feedback.set_problem_result("failed", "git-branch-merge")
    feedback.set_problem_feedback(feedback_str, "git-branch-merge")
else:
    grade -= 100.

feedback.set_grade(grade)
feedback.set_global_result("success" if grade == 100 else "failed")
feedback.set_global_feedback(_("Bien joué !") if grade == 100 else _("Il y a des erreurs dans vos réponses"))
