#!/bin/python3

import os
import sys
import subprocess

from inginious import feedback

lib_folder = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                          "$common/git_unittest")
sys.path.append(lib_folder)
lib_folder = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                          "/course/common/git_unittest")
sys.path.append(lib_folder)
from utils import _, unzip_task, unzip_solution

grade = 100.0

# Git-add subproblem
student_submission = unzip_task(task_id="git-add", expected_subpaths=["clone", "clone/.git"])
solution = unzip_solution(task_id="git-add")
if student_submission is not None:
    cmd = ["python3", "/course/common/git_unittest/test.py", os.path.join(solution, "clone"), os.path.join(student_submission, "clone")]
    pid = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    out, err = pid.communicate()
    if pid.wait() == 0:
        feedback.set_problem_result("success", "git-add")
        feedback.set_problem_feedback(_("Bonne réponse"), "git-add")
    else:
        feedback.set_problem_result("failed", "git-add")
        feedback.set_problem_feedback(err.decode("utf-8"), "git-add")
        grade -= 100.
else:
    grade -= 100.

feedback.set_grade(grade)
feedback.set_global_result("success" if grade == 100 else "failed")
feedback.set_global_feedback(_("Bien joué !") if grade == 100 else _("Il y a des erreurs dans vos réponses"))
